name: Sync from Hugging Face to GitHub

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Git LFS
        run: git lfs install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url space https://woodmastr:$HF_TOKEN@huggingface.co/spaces/woodmastr/imager
          git fetch space

      - name: Merge Hugging Face changes
        run: |
          git merge space/main --allow-unrelated-histories -X theirs

      - name: Push to GitHub
        run: git push origin main
